name: call_log_capturer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.0.0
  phone_state: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  call_log: ^3.0.3
  flutter_background_service: ^3.0.0

flutter:
  uses-material-design: true
